version: '3.8'

services:
  web:
    image: ysf-chatbot:latest
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always
    volumes:
      # Mount data directory to persist vector database
      - ./data:/app/data
